### ISSUE TITLE
Add Option to import JSON as-is

### ISSUE THREAD

**Issue by tglunde** [exasol/kafka-connector-extension#16]
Having an option to import the JSON from the kafka message as-is into a VARCHAR(2000000) field will provide more flexibility to read JSON data downstream using JSON functions JSON_VALUE and JSON_EXTRACT. We are currently implementing this and would like to provide a pull request once finished.

**Comment by morazow** [comment]
Hello @tglunde,

Thanks for the feedback!

We are in works to support this option. 

Please check out the recent pull request [#12](https://github.com/exasol/import-export-udf-common-scala/pull/12) in common library. Once the [#13](https://github.com/exasol/import-export-udf-common-scala/issues/13) is merged, we are going to release a new version of Kafka connector.

**Comment by morazow** [comment]
Hey @tglunde,

I have totally misread your comment.

That is great news! Storing the Avro schema as an additional metadata would help!

Please feel free to send the pull request!

**Comment by morazow** [comment]
Hey @ilikutle, @tglunde,

Thanks again! This is now merged in #18.

**Comment by tglunde** [comment]
Cool, thx! What is the current road map to releasing this?

**Comment by morazow** [comment]
I want to update the Kafka versions (#14) so that it is included in the next release.

But we do not have to wait for it, please let me know if you prefer another release early.

**Comment by morazow** [comment]
Hey @tglunde, @ilikutle,

I have released a new version that includes these changes! Please give it a try!

And thanks for your contributions!
