### ISSUE TITLE
Import raw JSON from Kafka

### ISSUE THREAD

**Issue by baunz** [exasol/kafka-connector-extension#24]
Hi,

I wonder if this library would be the right place to import raw JSON from kafka into a single column. This is a common use case as a lot of engineering teams place their messages on kafka using this format. Working with JSON data in Exasol is easy nowadays and more convenient.

This would require changes in the deserialization (no schema registry but plain StringDeserializer) but the rest is pretty the same and one could omit the schema registry url.

Greetings,
Johannes

**Comment by morazow** [comment]
Hello @baunz,

Yes, this would be the connector to use.

Please check out the user guide on setting up the UDFs, and running the importer. You can use the parameter `AS_JSON_DOC`, when it is set, it will import whole JSON into single column.

Let us know if there are any issues or questions.

Best

**Comment by baunz** [comment]
Hi @morazow,

thanks for the quick response. 

I meant importing _raw_ JSON - if I read the code correctly the `AS_JSON_DOC` parameter only transforms an already existing GenericRecord to it's JSON representation, but in our case the message format is not Confluent-Schema-Registry-Encoded-Avro but plain JSON, meaning "String".

To be honest I understood the documentation wrong for the first time and expected the connector to already work this way - I found out by trying out the UDFs

Cheers,
Johannes

**Comment by morazow** [comment]
Hey @baunz,

Sorry, I have missed your reply.

Yes, for the connector to work we require Schema Registry.

**Comment by baunz** [comment]
Hi @morazow ,

thanks for the answer! I think it would be a valuable addition to also support JSON Records - I will open a pull request soon to sketch how it could look like. 
One question though: I keep struggling with the logging - where can theoutput of the  logger.info(..) statements from the code be found - only on the nodes of the exasol?

Johannes

**Comment by morazow** [comment]
Hello @baunz,

Since these are based on the Exasol UDFs, you can redirect the logs. 

Open a listener, netcat in one of the Exasol nodes:

```
nc -lkp 3000
```

And set script output just before running SQL command:

```
ALTER SESSION SET SCRIPT_OUTPUT_ADDRESS='10.0.0.10:3000';
```

Change `10.0.0.10` to one of the internal node id addresses. You could also use `n10`, `n11` like domain names.

On the netcat terminal you should be able to see the logs from the UDF.

**Comment by baunz** [comment]
@morazow 

Thanks a lot for your help and feedback! I have two (very small!) additional features I will address in new pull requests, but that is something for next week...enjoy your weekend!

**Comment by morazow** [comment]
Hey @baunz,

That is great! Please send them. 

Thanks, have nice weekend too!
